const LV={
'Home':'Sākums','Name':'Nosaukums','· in progress':'· notiek','· next':'· nākamais','Logs':'Žurnāls','Progress':'Progress','Settings':'Iestatījumi','+ Day':'+ Diena','+ Exercise':'+ Vingrinājums','Anything worth remembering?':'Vai ir kas ievērības cienīgs?','Back to Home':'Atpakaļ uz sākumu','Difficulty':'Grūtība','Equipment':'Inventārs','Exercise type':'Vingrinājuma veids','Ramp-up':'Iesildīšanās piegājieni','REST':'ATPŪTA','Save set':'Saglabāt piegājienu','Undo last set':'Atsaukt pēdējo piegājienu','Workout frequency timeline':'Treniņu biežuma laika skala','Workout not found.':'Treniņš nav atrasts.','Enter the weight written on one dumbbell. Pair exercises count both dumbbells in volume.':'Ievadi uz vienas hanteles norādīto svaru. Pāra vingrinājumos apjoma aprēķinā tiek ņemtas vērā abas hanteles.','Programme':'Programma','Manual':'Pamācība','Quick manual':'Īsā pamācība',
'Workout':'Treniņš','Workout rotation':'Treniņu secība','Workout days and exercises':'Treniņu dienas un vingrinājumi','Workout frequency':'Treniņu biežums','Workout in progress':'Notiek treniņš','WORKOUT IN PROGRESS':'NOTIEK TRENIŅŠ','WORKOUT COMPLETE':'TRENIŅŠ PABEIGTS',
'No programme yet':'Programma vēl nav izveidota','Create programme':'Izveidot programmu','No exercises':'Nav vingrinājumu','No completed sessions yet.':'Vēl nav pabeigtu treniņu.','Recorded workouts will appear here.':'Šeit parādīsies saglabātie treniņi.',
'Exercise':'Vingrinājums','Exercises':'Vingrinājumi','Sets':'Piegājieni','Set':'Piegājiens','Reps':'Atkārtojumi','reps':'atkārtojumi','Rest':'Atpūta','Weight':'Svars','Volume':'Apjoms','Duration':'Ilgums','Current':'Pašlaik','First':'Pirmais','Recent':'Nesen','Period':'Periods','From':'No','To':'Līdz','Custom':'Pielāgots',
'Failure':'Atteice','Aborted':'Pārtraukts','Skipped':'Izlaists','Comfortable':'Komfortabls','Challenging':'Izaicinošs','Hard':'Smags','Very hard':'Ļoti smags','Moderate':'Mērens','Easy':'Viegls',
'Warm-up':'Iesildīšanās','WARM-UP':'IESILDĪŠANĀS','Stretching':'Stiepšanās','STRETCHING':'STIEPŠANĀS','RAMP-UP':'IESILDĪŠANĀS PIEGĀJIENI','Suggested ramp-up':'Ieteiktie iesildīšanās piegājieni','START RAMP-UP':'SĀKT IESILDĪŠANĀS PIEGĀJIENUS','FINISH RAMP-UP':'PABEIGT IESILDĪŠANĀS PIEGĀJIENUS','REMOVE WEIGHTS':'NOŅEMT SVARUS','SET IN PROGRESS':'NOTIEK PIEGĀJIENS','SET COMPLETE':'PIEGĀJIENS PABEIGTS','SAVE SET':'SAGLABĀT PIEGĀJIENU','FINISH & SAVE':'PABEIGT UN SAGLABĀT',
'Back':'Atpakaļ','Save':'Saglabāt','Create':'Izveidot','Add':'Pievienot','Add exercise':'Pievienot vingrinājumu','Edit exercise':'Rediģēt vingrinājumu','Rename workout':'Pārdēvēt treniņu','New workout day':'Jauna treniņa diena','Done':'Pabeigts','Log':'Žurnāls','Reschedule':'Pārplānot','Restore':'Atjaunot','Working weight':'Darba svars','per dumbbell':'vienai hantelei','A workout is already active':'Treniņš jau notiek','Add at least one exercise first.':'Vispirms pievieno vismaz vienu vingrinājumu.','All data erased':'Visi dati dzēsti','Backup restored':'Rezerves kopija atjaunota','Browser notifications are not available here':'Pārlūka paziņojumi šeit nav pieejami','Can’t start workout':'Treniņu nevar sākt','Delete this workout?':'Dzēst šo treniņu?','Erase all data?':'Dzēst visus datus?','Final warning':'Pēdējais brīdinājums','Finish stretching':'Pabeigt stiepšanos','Finish warm-up':'Pabeigt iesildīšanos','Historical workout data is not affected.':'Iepriekšējo treniņu dati netiek ietekmēti.','Invalid file':'Nederīgs fails','Notifications enabled':'Paziņojumi ieslēgti','Notifications not enabled':'Paziņojumi nav ieslēgti','Restore backup?':'Atjaunot rezerves kopiju?','The selected file is not valid JSON.':'Izvēlētais fails nav derīgs JSON.','There is no undo. Cancel now if you need to create a backup first.':'Šo darbību nevar atsaukt. Atcel, ja vispirms jāizveido rezerves kopija.','This deletes the workout template. Historical completed sessions are kept.':'Tiks dzēsta treniņa sagatave. Iepriekš pabeigtie treniņi tiks saglabāti.','This is not a supported Gym Progress backup.':'Šī nav atbalstīta Gym Progress rezerves kopija.','This permanently deletes your programme, working weights, settings and complete training history from this PWA. Recovery is possible only from a full backup you already saved.':'Tas neatgriezeniski dzēsīs programmu, darba svarus, iestatījumus un visu treniņu vēsturi no šīs PWA. Atjaunošana iespējama tikai no iepriekš saglabātas pilnas rezerves kopijas.','This removes the complete session and all of its recorded sets. This cannot be undone.':'Tiks dzēsta visa treniņa sesija un visi tajā saglabātie piegājieni. Šo darbību nevar atsaukt.','This replaces all current data in this PWA with the selected backup.':'Visi pašreizējie dati šajā PWA tiks aizstāti ar izvēlēto rezerves kopiju.','Unsupported backup':'Neatbalstīta rezerves kopija','Workout names must be unique':'Treniņu nosaukumiem jābūt unikāliem','You’ll move to stretching after the programmed rest.':'Pēc paredzētās atpūtas pāriesi uz stiepšanos.','Continue':'Turpināt','Delete':'Dzēst','Cancel':'Atcelt','Close':'Aizvērt','Skip':'Izlaist','Apply':'Piemērot','Keep current':'Atstāt pašreizējo','Use next time':'Izmantot nākamreiz','Apply next set':'Piemērot nākamajam piegājienam','Start anyway':'Sākt tomēr','Start workout':'Sākt treniņu','Return to workout':'Atgriezties treniņā',
'Training':'Treniņš','Training effort':'Treniņa piepūle','Default target is 1–2 RIR. Extend the scale only if your training deliberately stays farther from failure.':'Noklusējuma mērķis ir 1–2 RIR. Paplašini skalu tikai tad, ja apzināti trenējies tālāk no atteices.','Target RIR minimum':'Minimālais mērķa RIR','Target RIR maximum':'Maksimālais mērķa RIR','RIR input scale':'RIR ievades skala','Compact · 3+':'Kompakta · 3+','Extended · 5+':'Paplašināta · 5+',
'Increase-weight threshold':'Svara palielināšanas slieksnis','Every required set must reach its rep target with at least this RIR and no failures.':'Katram vajadzīgajam piegājienam jāsasniedz atkārtojumu mērķis ar vismaz šo RIR un bez atteices.','Difficulty levels':'Grūtības līmeņi','Comfortable / challenging / hard thresholds':'Komfortabla / izaicinoša / smaga treniņa sliekšņi',
'Motivation & reminders':'Motivācija un atgādinājumi','Optional inactivity and next-session reminders':'Izvēles atgādinājumi par neaktivitāti un nākamo treniņu','No workout for (days)':'Bez treniņa (dienas)','Evening-before reminder':'Atgādinājums iepriekšējā vakarā','Workout-day reminder':'Atgādinājums treniņa dienā','Allow browser notifications':'Atļaut pārlūka paziņojumus','PWA note: scheduled notifications are best effort. A static GitHub Pages PWA may not be woken by iOS/desktop browsers while fully closed.':'PWA piezīme: ieplānotie paziņojumi ir iespējami pēc labākās iespējas. Statiska GitHub Pages PWA var netikt pamodināta, ja iOS vai datora pārlūks ir pilnībā aizvērts.',
'Shown in your selected app language':'Tiek rādīta izvēlētajā lietotnes valodā','Keep screen awake':'Treniņa laikā neatspējot ekrānu','Export detailed JSON':'Eksportēt detalizētu JSON','No workout days yet.':'Vēl nav izveidota neviena treniņu diena.','No recorded workouts yet.':'Vēl nav saglabātu treniņu.','Effort':'Piepūle','Volume progress':'Apjoma progress','Dumbbells':'Hanteles','Rest (seconds)':'Atpūta (sekundes)','Remove weights after exercise':'Pēc vingrinājuma noņemt svarus','Working weight (kg)':'Darba svars (kg)','Working weight per dumbbell (kg)':'Darba svars vienai hantelei (kg)','Start ramp-up':'Sākt iesildīšanās piegājienus','Finish ramp-up':'Pabeigt iesildīšanās piegājienus','Shortened because a similar movement is already warm.':'Saīsināts, jo līdzīga kustība jau ir iesildīta.','No ramp-up sets suggested.':'Iesildīšanās piegājieni nav nepieciešami.','Optional workout note':'Piezīme par treniņu (nav obligāta)','Skip set':'Izlaist piegājienu','Skip exercise':'Izlaist vingrinājumu','Could not start':'Neizdevās sākt','All required sets reached target reps with enough RIR and no failures.':'Visos vajadzīgajos piegājienos sasniegts atkārtojumu mērķis ar pietiekamu RIR un bez atteices.','1 month':'1 mēnesis','3 months':'3 mēneši','6 months':'6 mēneši','1 year':'1 gads','5 years':'5 gadi','30 days':'30 dienas','No active workout.':'Nav aktīva treniņa.','Delete this workout':'Dzēst šo treniņu','Warm-up skipped':'Iesildīšanās izlaista','Stretching skipped':'Stiepšanās izlaista','RAMP-UP · skipped':'IESILDĪŠANĀS PIEGĀJIENI · izlaisti','Your starter programme is ready.':'Sākuma programma ir gatava.','Comfortable starts at average RIR':'Komfortabls sākas no vidējā RIR','Challenging starts at':'Izaicinošs sākas no','Hard starts at':'Smags sākas no','No data in this period.':'Šajā periodā nav datu.','Data':'Dati','Full backup':'Pilna rezerves kopija','Restore backup':'Atjaunot no rezerves kopijas','Export CSV':'Eksportēt CSV','Export JSON':'Eksportēt JSON','Erase all data':'Dzēst visus datus','Keep screen awake in workouts':'Treniņa laikā neatspējot ekrānu',
'Language':'Valoda','English':'English','Latviešu':'Latviešu','Starter programme':'Sākuma programma','Set up starter programme':'Izveidot sākuma programmu','Adds three editable workout days. Your existing programme is kept.':'Pievieno trīs rediģējamas treniņu dienas. Esošā programma tiek saglabāta.',
'I don’t have a programme yet':'Man vēl nav programmas','I don\'t have a programme yet':'Man vēl nav programmas','You do not have any workout days yet. I can build a simple three-day starter programme, or you can create your own.':'Tev vēl nav nevienas treniņu dienas. Varu izveidot vienkāršu trīs dienu sākuma programmu, vai arī vari izveidot savu.','Set it up for me':'Izveido man','Set up manually':'Izveidot manuāli','Not now':'Ne tagad',
'Starter programme setup':'Sākuma programmas izveide','Goal':'Mērķis','Experience':'Pieredze','Starting weights':'Sākuma svari','Strength':'Spēks','Muscle gain':'Muskuļu masas palielināšana','General fitness / tone':'Vispārējā fiziskā forma / tonuss','Conditioning / cardio support':'Kondīcija / kardio papildinājums','Beginner · under 6 months':'Iesācējs · mazāk par 6 mēnešiem','Some experience · 6–24 months':'Neliela pieredze · 6–24 mēneši','Experienced · 2+ years':'Pieredzējis · 2+ gadi','Next':'Tālāk','Build programme':'Izveidot programmu',
'Enter a comfortable weight you could lift for about 8 good reps. This is not a max test. Leave a field blank if you are unsure; you can edit every starting weight later.':'Ievadi komfortablu svaru, ar kuru vari izpildīt aptuveni 8 kvalitatīvus atkārtojumus. Tas nav maksimālā svara tests. Ja neesi drošs, lauku vari atstāt tukšu; visus sākuma svarus vēlāk var rediģēt.','This wizard creates a general starting point, not a medical or individually coached prescription. You can edit everything afterwards.':'Šis vednis izveido vispārīgu sākumpunktu, nevis medicīnisku vai individuāla trenera sastādītu programmu. Pēc tam visu vari rediģēt.','Conditioning / cardio support changes the resistance-training prescription; it does not replace dedicated aerobic training.':'Kondīcijas / kardio papildinājuma izvēle maina spēka treniņa uzbūvi; tā neaizstāj atsevišķu aerobo treniņu.','Squat':'Pietupiens','Bench press':'Spiešana guļus','Row':'Vilkšana pie jostas','Romanian deadlift':'Rumāņu vilkme',
'Ready to progress':'Gatavs progresēt','Bodyweight progression increases the rep target rather than adding kilograms.':'Vingrinājumos ar ķermeņa svaru progresija palielina atkārtojumu mērķi, nevis kilogramus.','Next target reps':'Nākamais atkārtojumu mērķis','Next working weight':'Nākamais darba svars','Make next time a little easier?':'Nākamreiz nedaudz vieglāk?','Suggested next target':'Ieteiktais nākamais mērķis',
'This exercise reached failure. A slightly lower rep target next time may fit your current capacity better.':'Šajā vingrinājumā tika sasniegta atteice. Nedaudz mazāks atkārtojumu mērķis nākamreiz var labāk atbilst pašreizējām spējām.','Several sets reached failure. A slightly lower rep target next time may make the exercise more sustainable.':'Vairākos piegājienos tika sasniegta atteice. Nedaudz mazāks atkārtojumu mērķis nākamreiz var palīdzēt saglabāt ilgtspējīgu slodzi.','This exercise reached failure. A small working-weight reduction next time may be more appropriate.':'Šajā vingrinājumā tika sasniegta atteice. Nākamreiz varētu būt piemērotāks nedaudz mazāks darba svars.','Several sets reached failure. A small working-weight reduction next time may keep the exercise closer to the intended effort.':'Vairākos piegājienos tika sasniegta atteice. Neliels darba svara samazinājums nākamreiz var palīdzēt saglabāt paredzēto piepūles līmeni.',
'Next session?':'Nākamais treniņš?','Reschedule next session':'Pārplānot nākamo treniņu','Suggested date:':'Ieteiktais datums:','Date':'Datums','Schedule':'Ieplānot','Save date':'Saglabāt datumu','Clear schedule':'Dzēst ieplānoto','Next session scheduled':'Nākamais treniņš ieplānots',
'Ready for another session?':'Gatavs nākamajam treniņam?','Gym tomorrow':'Treniņš rīt','Your next session is planned for tomorrow.':'Nākamais treniņš ir ieplānots rīt.','Planned session is due':'Ieplānotais treniņš ir pienācis','Gym today':'Treniņš šodien','Your planned gym session is now overdue.':'Ieplānotais treniņš ir nokavēts.','Your next session is planned for today.':'Nākamais treniņš ir ieplānots šodien.',
'Workout saved':'Treniņš saglabāts','Workout saved as partial':'Nepilnais treniņš saglabāts','Workout discarded':'Treniņš atmests','Next set adjusted':'Nākamais piegājiens pielāgots','Nothing to undo':'Nav ko atsaukt','Last set restored':'Pēdējais piegājiens atjaunots',
'End workout early?':'Beigt treniņu priekšlaicīgi?','Finish as partial':'Pabeigt kā nepilnu','Discard workout':'Atmest treniņu','Finish as partial keeps completed work, marks every remaining set/exercise skipped, and shows this workout in Logs as Aborted.':'Pabeidzot kā nepilnu, paveiktais tiek saglabāts, atlikušie piegājieni un vingrinājumi tiek atzīmēti kā izlaisti, bet Žurnālā treniņš redzams kā Pārtraukts.','Discard workout removes this session completely and it will not appear in Logs or Progress.':'Atmetot treniņu, šī sesija tiek pilnībā dzēsta un neparādās ne Žurnālā, ne Progresā.',
'Install on iPhone':'Instalēt iPhone','In Safari: Share → Add to Home Screen → Add.':'Safari: Kopīgot → Pievienot sākuma ekrānam → Pievienot.','Drag · pinch to zoom':'Velc · savelc, lai tuvinātu','No data in this period.':'Šajā periodā nav datu.','Custom range':'Pielāgots periods',
'Barbell':'Stienis','Dumbbell':'Hantele','Machine':'Trenažieris','Cable':'Trošu trenažieris','Bodyweight':'Ķermeņa svars','Other':'Cits','Pair':'Pāris','Single':'Viena',
'Heavy compound':'Smags daudzlocītavu','Moderate compound':'Vidēji smags daudzlocītavu','Machine/accessory compound':'Trenažiera/papildu daudzlocītavu','Isolation':'Izolējošs','Automatic':'Automātiski','Always':'Vienmēr','Never':'Nekad',
'Barbell Bench Press':'Spiešana guļus ar stieni','Back Squat':'Pietupiens ar stieni','Deadlift':'Vilce','Sumo Deadlift':'Sumo vilce','Front Squat':'Priekšējais pietupiens','Barbell Overhead Press':'Spiešana virs galvas ar stieni','Incline Barbell Bench Press':'Spiešana slīpi guļus ar stieni','Romanian Deadlift':'Rumāņu vilkme','Barbell Row':'Vilkšana pie jostas ar stieni','Barbell Hip Thrust':'Gurnu pacelšana ar stieni','Leg Press':'Kāju spiešana','Hack Squat':'Hack pietupiens','Machine Chest Press':'Krūšu spiešana trenažierī','Lat Pulldown':'Augšējā bloka vilkšana','Seated Cable Row':'Sēdus vilkšana pie jostas trosē','Machine Shoulder Press':'Plecu spiešana trenažierī','Dumbbell Bench Press':'Spiešana guļus ar hantelēm','Incline Dumbbell Press':'Spiešana slīpi guļus ar hantelēm','Dumbbell Shoulder Press':'Plecu spiešana ar hantelēm','Pull-up':'Pievilkšanās','Bulgarian Split Squat':'Bulgāru pietupiens','Leg Extension':'Kāju iztaisnošana','Leg Curl':'Kāju saliekšana','Lateral Raise':'Sānu pacelšana','Biceps Curl':'Bicepsa saliekšana','Triceps Pushdown':'Tricepsa spiešana uz leju','Calf Raise':'Pacelšanās uz pirkstgaliem','Pec Deck':'Krūšu savilkšana trenažierī','Cable Fly':'Krūšu savilkšana trosēs',
'Choose RIR or Failure before saving.':'Pirms saglabāšanas izvēlies RIR vai Atteici.',
'Some starting weights are missing':'Trūkst dažu sākuma svaru','No starting weights were entered. I can still create a conservative estimated baseline, but it will be less personal.':'Nav ievadīts neviens sākuma svars. Varu izveidot piesardzīgu aptuvenu sākumpunktu, taču tas būs mazāk individuāls.','I can estimate the missing movements from the weights you entered. The starter programme will be based on limited data and should be adjusted if anything feels clearly too light or too heavy.':'Trūkstošos vingrinājumu svarus varu aptuveni aprēķināt no ievadītajiem svariem. Sākuma programma balstīsies uz ierobežotiem datiem, tāpēc to vajadzēs koriģēt, ja kāds svars šķiet nepārprotami par vieglu vai par smagu.','Missing:':'Trūkst:','Go back and complete':'Atpakaļ un papildināt','Build with estimates':'Izveidot ar aprēķiniem',
'Bodyweight · no external load':'Ķermeņa svars · bez ārējas slodzes','Working weight must be greater than 0 kg.':'Darba svaram jābūt lielākam par 0 kg.',
'Failure came on the first set and reps were well below target. Keep the rep target and reduce the next load.':'Atteice notika jau pirmajā piegājienā, un atkārtojumu mērķis būtiski netika sasniegts. Saglabā atkārtojumu mērķi un nākamajā piegājienā samazini svaru.',
'Failure came on the first set, before normal set-to-set fatigue should dominate. Keep the rep target and reduce the next load slightly.':'Atteice notika jau pirmajā piegājienā, pirms uzkrātajam nogurumam vajadzētu būt galvenajam faktoram. Saglabā atkārtojumu mērķi un nākamajā piegājienā nedaudz samazini svaru.',
'Failure came on the first set and reps were well below target. Reduce the next rep target.':'Atteice notika jau pirmajā piegājienā, un atkārtojumu mērķis būtiski netika sasniegts. Samazini nākamā piegājiena atkārtojumu mērķi.',
'Failure came on the first set. Reduce the next rep target slightly.':'Atteice notika jau pirmajā piegājienā. Nedaudz samazini nākamā piegājiena atkārtojumu mērķi.',
'Failure is repeating or the rep target was missed by several reps. Keep the rep target and reduce load for the next set.':'Atteice atkārtojas vai atkārtojumu mērķis nav sasniegts par vairākiem atkārtojumiem. Saglabā atkārtojumu mērķi un nākamajā piegājienā samazini svaru.',
'Failure is repeating or the rep target was missed by several reps. Reduce the next bodyweight rep target.':'Atteice atkārtojas vai atkārtojumu mērķis nav sasniegts par vairākiem atkārtojumiem. Samazini nākamā ķermeņa svara piegājiena atkārtojumu mērķi.',
'A later set reached failure near the rep target. Keep the rep target and reduce the next load slightly.':'Vēlākā piegājienā atteice sasniegta tuvu atkārtojumu mērķim. Saglabā atkārtojumu mērķi un nākamajā piegājienā nedaudz samazini svaru.',
'A later bodyweight set reached failure near the rep target. Trim one rep from the next target.':'Vēlākā ķermeņa svara piegājienā atteice sasniegta tuvu atkārtojumu mērķim. Nākamā piegājiena mērķi samazini par vienu atkārtojumu.',
'The set finished several reps below target. Keep the rep target and reduce the next load slightly.':'Piegājiens pabeigts vairākus atkārtojumus zem mērķa. Saglabā atkārtojumu mērķi un nākamajā piegājienā nedaudz samazini svaru.',
'The set finished several reps below target. Reduce the next bodyweight rep target slightly.':'Piegājiens pabeigts vairākus atkārtojumus zem mērķa. Nedaudz samazini nākamā ķermeņa svara piegājiena atkārtojumu mērķi.',
'The first set was closer to failure than your target RIR range. Keep the rep target and reduce the next load slightly.':'Pirmais piegājiens bija tuvāk atteicei nekā paredzētais RIR diapazons. Saglabā atkārtojumu mērķi un nākamajā piegājienā nedaudz samazini svaru.',
'The first set was closer to failure than your target RIR range. Trim one rep from the next bodyweight target.':'Pirmais piegājiens bija tuvāk atteicei nekā paredzētais RIR diapazons. Nākamā ķermeņa svara piegājiena mērķi samazini par vienu atkārtojumu.',
'RIR dropped sharply compared with the previous set. Keep the rep target and reduce the next load slightly.':'RIR strauji samazinājās salīdzinājumā ar iepriekšējo piegājienu. Saglabā atkārtojumu mērķi un nākamajā piegājienā nedaudz samazini svaru.',
'RIR dropped sharply compared with the previous set. Trim one rep from the next bodyweight target.':'RIR strauji samazinājās salīdzinājumā ar iepriekšējo piegājienu. Nākamā ķermeņa svara piegājiena mērķi samazini par vienu atkārtojumu.',
'Two sets in a row are harder than your target RIR range. Keep the rep target and use a small load reduction for the next set.':'Divi piegājieni pēc kārtas ir smagāki par paredzēto RIR diapazonu. Saglabā atkārtojumu mērķi un nākamajā piegājienā nedaudz samazini svaru.',
'Two bodyweight sets in a row are harder than your target RIR range. Trim one rep from the next target.':'Divi ķermeņa svara piegājieni pēc kārtas ir smagāki par paredzēto RIR diapazonu. Nākamā piegājiena mērķi samazini par vienu atkārtojumu.',
'This set reached 0 RIR while your target is farther from failure. Keep the rep target and reduce the next load slightly.':'Šajā piegājienā sasniegts 0 RIR, lai gan mērķis paredz lielāku rezervi. Saglabā atkārtojumu mērķi un nākamajā piegājienā nedaudz samazini svaru.',
'This bodyweight set reached 0 RIR while your target is farther from failure. Trim one rep from the next target.':'Šajā ķermeņa svara piegājienā sasniegts 0 RIR, lai gan mērķis paredz lielāku rezervi. Nākamā piegājiena mērķi samazini par vienu atkārtojumu.',
'Several sets reached failure. Reduce the rep target slightly next time while keeping the bodyweight movement unchanged.':'Vairāki piegājieni sasniedza atteici. Nākamreiz nedaudz samazini atkārtojumu mērķi, saglabājot to pašu ķermeņa svara vingrinājumu.',
'This bodyweight exercise reached failure. Reduce the rep target slightly next time.':'Šajā ķermeņa svara vingrinājumā sasniegta atteice. Nākamreiz nedaudz samazini atkārtojumu mērķi.',
'Drag the grip to reorder.':'Velc aiz roktura, lai mainītu secību.','Drag to reorder':'Velc, lai mainītu secību','Erase exercise log data':'Dzēst treniņu žurnāla datus','Erase exercise log data?':'Dzēst treniņu žurnāla datus?','This permanently deletes workout history, recorded sets and Progress data. Your programme, settings and current working weights are kept.':'Tas neatgriezeniski dzēsīs treniņu vēsturi, saglabātos piegājienus un Progresa datus. Programma, iestatījumi un pašreizējie darba svari tiks saglabāti.','ERASE LOGS':'DZĒST ŽURNĀLU','Exercise log data erased':'Treniņu žurnāla dati dzēsti'
};

export function languageCode(state){return state?.app_state?.languageCode==='lv'?'lv':'en';}
export function localeFor(lang){return lang==='lv'?'lv-LV':'en-GB';}
export function t(raw,lang='en'){
  raw=String(raw??'');if(lang!=='lv'||!raw)return raw;
  if(LV[raw]!=null)return LV[raw];
  let m;
  if((m=/^(\d+) exercises?$/.exec(raw)))return `${m[1]} ${Number(m[1])===1?'vingrinājums':'vingrinājumi'}`;
  if((m=/^(\d+) days?$/.exec(raw)))return `${m[1]} ${Number(m[1])===1?'diena':'dienas'}`;
  if((m=/^(\d+) weeks?$/.exec(raw)))return `${m[1]} ${Number(m[1])===1?'nedēļa':'nedēļas'}`;
  if((m=/^(\d+) months?$/.exec(raw)))return `${m[1]} ${Number(m[1])===1?'mēnesis':'mēneši'}`;
  if((m=/^(\d+(?:\.\d+)?) years?$/.exec(raw)))return `${m[1]} gadi`;
  if((m=/^(\d+) reps$/.exec(raw)))return `${m[1]} atkārtojumi`;
  if((m=/^SET (\d+)\/(\d+) SKIPPED$/.exec(raw)))return `${m[1]}. PIEGĀJIENS/${m[2]} IZLAISTS`;
  if((m=/^SET (\d+) \/ (\d+)$/.exec(raw)))return `${m[1]}. PIEGĀJIENS / ${m[2]}`;
  if((m=/^Suggested set (\d+)$/.exec(raw)))return `Ieteiktais ${m[1]}. piegājiens`;
  if((m=/^Suggested increase: (.+)$/.exec(raw)))return `Ieteiktais palielinājums: ${m[1]}`;
  if((m=/^Volume (.+)$/.exec(raw)))return `Apjoms ${m[1]}`;
  if((m=/^(.+) progress$/.exec(raw)))return `${t(m[1],lang)} progress`;
  if((m=/^Start (.+)\?$/.exec(raw)))return `Sākt ${t(m[1],lang)}?`;
  if((m=/^Skip (.+)\?$/.exec(raw)))return `Izlaist ${t(m[1],lang)}?`;
  if((m=/^(.+) SKIPPED · NEXT: (.+)$/.exec(raw)))return `${t(m[1],lang)} IZLAISTS · TĀLĀK: ${t(m[2],lang)}`;
  if((m=/^(.+) SKIPPED$/.exec(raw)))return `${t(m[1],lang)} IZLAISTS`;
  if((m=/^It’s been (\d+) (day|days) since your last recorded workout\.$/.exec(raw)))return `Kopš pēdējā saglabātā treniņa pagājušas ${m[1]} ${Number(m[1])===1?'diena':'dienas'}.`;
  if((m=/^(.+) · in progress$/.exec(raw)))return `${m[1]} · notiek`;
  if((m=/^(.+) · next(?: · (.+))?$/.exec(raw)))return `${m[1]} · nākamais${m[2]?` · ${m[2]}`:''}`;
  return raw;
}

export function localizeDom(root,lang='en'){
  document.documentElement.lang=lang;
  if(lang!=='lv')return;
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
  while((node=walker.nextNode())){const raw=node.nodeValue||'',trim=raw.trim();if(!trim)continue;const translated=t(trim,lang);if(translated!==trim)node.nodeValue=raw.replace(trim,translated);}
  root.querySelectorAll?.('[aria-label],[title],[placeholder]').forEach(el=>{
    for(const attr of ['aria-label','title','placeholder']){const v=el.getAttribute(attr);if(v)el.setAttribute(attr,t(v,lang));}
  });
}
