const EN=[
  ['Start & programme','No programme yet? Use the three-day starter wizard or build your own. Loaded exercises need a weight above 0 kg; barbell weight is total bar weight, dumbbell weight is one dumbbell, and bodyweight exercises use reps instead of kg. Drag the grip to reorder days or exercises. Programme edits never rewrite past workouts.'],
  ['Workout flow','Warm-up → ramp-up → working sets and rest → optional unload → stretching. Automatic ramp-up is recommended because it adapts to the exercise, working weight, rep target and similar work already completed in the session.'],
  ['Saving a set','Press SET COMPLETE and rest starts immediately while you enter the result. Count only fully completed reps. Before saving, choose either RIR or Failure; RIR means how many good reps you believe were still possible.'],
  ['Coaching & progression','Unexpected failure or a large effort drop can trigger advice. Loaded exercises keep their rep target and reduce weight; bodyweight exercises reduce reps. Future-session reduced weight can be edited before applying. Successful sets can trigger progression, and progression suggestions remain editable too.'],
  ['Logs & progress','Finish as partial saves completed work as Aborted; Discard workout removes the active session. Aborted sessions stay out of Progress baselines. Logs show history and difficulty; Progress tracks Weight, Volume and e1RM. The frequency timeline fits first workout → today while history is shorter than about a month.'],
  ['Friends','Friends is optional and does not sync or expose your private programme or log. Sign in with an e-mail code, add people by exact e-mail and accept mutual friend requests. Requests and acceptances create Friends notifications; accepted friends can be removed for both users. After a workout, choose individual summary/record cards to publish; comments appear only on selected cards and nothing is shared automatically. Friends shows a shared 30-day rhythm and an activity feed.'],
  ['Scheduling','Motivation & reminders is optional. After a completed workout, Gym Progress can suggest the next training date; accept it, change it, reschedule it later or skip it. Reminder times are configurable. PWA notifications are best-effort when the browser is fully closed.'],
  ['Language','Choose English or Latvian in Settings. The whole interface and this Manual follow the selected language.'],
  ['Data & backups','Full backup is the restorable copy of programme, history and settings. CSV and detailed JSON are for analysis. Erase exercise log data clears workout history and Progress while keeping programme, settings and working weights; Erase all data removes everything local.']
];

const LV=[
  ['Sākšana un programma','Ja programmas vēl nav, izmanto trīs dienu sākuma vedni vai izveido savu. Vingrinājumiem ar ārēju slodzi svaram jābūt lielākam par 0 kg; stienim ievadi pilnu stieņa svaru, hantelēm — vienas hanteles svaru, bet ķermeņa svara vingrinājumos mērķis ir atkārtojumi, nevis kg. Dienas un vingrinājumus pārkārto, velkot aiz roktura. Programmas labojumi nemaina iepriekšējos treniņus.'],
  ['Treniņa plūsma','Iesildīšanās → iesildīšanās piegājieni → darba piegājieni un atpūta → pēc vajadzības svaru noņemšana → stiepšanās. Ieteicams automātiskais iesildīšanās piegājienu režīms, jo tas ņem vērā vingrinājumu, darba svaru, atkārtojumu mērķi un jau paveiktu līdzīgu darbu.'],
  ['Piegājiena saglabāšana','Nospied PIEGĀJIENS PABEIGTS, un atpūta sākas uzreiz, kamēr ievadi rezultātu. Uzskaiti tikai pilnībā pabeigtus atkārtojumus. Pirms saglabāšanas obligāti izvēlies RIR vai Atteici; RIR ir atkārtojumu rezerve — cik kvalitatīvus atkārtojumus vēl būtu iespējams izpildīt.'],
  ['Ieteikumi un progresija','Negaidīta atteice vai izteikts piepūles kritums var izraisīt ieteikumu. Vingrinājumiem ar ārēju slodzi atkārtojumu mērķis paliek nemainīgs un tiek samazināts svars; ķermeņa svara vingrinājumiem samazina atkārtojumus. Nākamajam treniņam piedāvāto samazināto svaru vari koriģēt pirms apstiprināšanas. Arī progresijas ieteikumi ir rediģējami.'],
  ['Žurnāls un progress','Pabeigt kā nepilnu saglabā paveikto un atzīmē treniņu kā Pārtrauktu; Atmest treniņu aktīvo sesiju dzēš. Pārtraukti treniņi netiek izmantoti Progresa bāzes salīdzinājumos. Žurnālā redzama vēsture un grūtība, bet Progresā — Svars, Apjoms un e1RM. Kamēr vēsture ir īsāka par aptuveni mēnesi, biežuma skala rāda periodu no pirmā treniņa līdz šodienai.'],
  ['Draugi','Draugu funkcija nav obligāta un nesinhronizē vai neatklāj tavu privāto programmu vai žurnālu. Pieslēdzies ar e-pastā saņemtu kodu, pievieno cilvēkus pēc precīza e-pasta un apstiprini savstarpējus draudzības uzaicinājumus. Uzaicinājumi un to apstiprinājumi veido Draugu paziņojumus; apstiprinātu draugu var noņemt abiem lietotājiem. Pēc treniņa izvēlies atsevišķas kopsavilkuma vai rekordu kartītes publicēšanai; komentārs parādās tikai izvēlētai kartītei un nekas netiek kopīgots automātiski. Draugu sadaļā redzams kopīgs 30 dienu ritms un aktivitāšu plūsma.'],
  ['Plānošana','Motivācija un atgādinājumi ir izvēles funkcija. Pēc pabeigta treniņa Gym Progress var ieteikt nākamā treniņa datumu; to vari pieņemt, mainīt, vēlāk pārplānot vai izlaist. Atgādinājumu laikus var mainīt. Ja PWA ir pilnībā aizvērta, pārlūka paziņojumi ir tikai pēc labākās iespējas.'],
  ['Valoda','Iestatījumos izvēlies angļu vai latviešu valodu. Visa lietotne un šī Pamācība seko izvēlētajai valodai.'],
  ['Dati un rezerves kopijas','Pilna rezerves kopija ir paredzēta programmas, vēstures un iestatījumu atjaunošanai. CSV un detalizētais JSON ir paredzēti analīzei. Dzēst treniņu žurnāla datus izdzēš vēsturi un Progresa datus, bet saglabā programmu, iestatījumus un darba svarus; Dzēst visus datus izdzēš visu lokālo informāciju.']
];

export function manualHtml(lang='en'){
  const items=lang==='lv'?LV:EN;
  const title=lang==='lv'?'Īsā pamācība':'Quick manual';
  const intro=lang==='lv'?'Svarīgākais par programmu, treniņu, kopīgošanu, ieteikumiem un datiem.':'The essentials: programme, workout, sharing, coaching and data.';
  return `<div class="manual-hero"><div class="manual-kicker">${lang==='lv'?'PAMĀCĪBA':'MANUAL'}</div><h1>${title}</h1><p>${intro}</p></div><div class="manual-guide">`+
    items.map(([heading,body],i)=>`<section class="manual-section"><div class="manual-section-head"><span class="manual-number">${String(i+1).padStart(2,'0')}</span><h2>${heading}</h2></div><p>${body}</p></section>`).join('')+
    `</div>`;
}
