const icon = (kind) => {
  const common='viewBox="0 0 120 82" aria-hidden="true"';
  if(kind==='programme') return `<svg ${common}><rect x="15" y="15" width="90" height="52" rx="12"/><line x1="32" y1="31" x2="88" y2="31"/><line x1="32" y1="43" x2="78" y2="43"/><circle cx="28" cy="56" r="5"/><circle cx="45" cy="56" r="5"/><circle cx="62" cy="56" r="5"/></svg>`;
  if(kind==='ramp') return `<svg ${common}><line x1="14" y1="67" x2="108" y2="67"/><rect x="20" y="52" width="16" height="15" rx="3"/><rect x="46" y="40" width="16" height="27" rx="3"/><rect x="72" y="27" width="16" height="40" rx="3"/><path d="M22 48 L50 35 L77 21 L101 10"/><path d="M92 10 L101 10 L99 19"/></svg>`;
  if(kind==='rir') return `<svg ${common}><path d="M18 57 A42 42 0 0 1 102 57"/><line x1="60" y1="57" x2="83" y2="29"/><circle cx="60" cy="57" r="5"/><text x="18" y="74">FAIL</text><text x="92" y="74">5+</text></svg>`;
  if(kind==='flag') return `<svg ${common}><line x1="35" y1="12" x2="35" y2="70"/><path d="M35 14 L91 20 L74 39 L35 34 Z"/><path d="M58 48 L68 58 L88 38" class="accent"/></svg>`;
  if(kind==='calendar') return `<svg ${common}><rect x="23" y="18" width="74" height="52" rx="10"/><line x1="23" y1="34" x2="97" y2="34"/><line x1="40" y1="12" x2="40" y2="25"/><line x1="80" y1="12" x2="80" y2="25"/><circle cx="47" cy="50" r="4" class="accent"/><path d="M59 50 L67 58 L82 43" class="accent"/></svg>`;
  return `<svg ${common}><circle cx="23" cy="41" r="10"/><line x1="33" y1="41" x2="49" y2="41"/><circle cx="60" cy="41" r="10"/><line x1="70" y1="41" x2="86" y2="41"/><circle cx="97" cy="41" r="10"/></svg>`;
};

const EN = [
  ['programme','Build your programme','Create workout days, then add exercises with sets, reps, rest and working weight. Set Equipment too. For dumbbells, enter the weight of one dumbbell and choose Pair or Single; Pair volume counts both dumbbells automatically. Heavy compound means demanding multi-joint lifts such as squat, deadlift or bench press. Compound is a less demanding multi-joint lift, Machine compound is guided by a machine, and Isolation mainly targets one joint or muscle.'],
  ['ramp','Let Automatic handle ramp-up','Exercise type matters because heavy lifts usually need more preparation. Automatic ramp-up uses the exercise, working weight and workout context. If a similar movement is already warm, it shortens the ramp-up. Use Always or Never only when you have a reason. “Remove weights” logs unloading separately instead of pretending it was passive rest.'],
  ['rir','Use RIR as your effort gauge','RIR means reps in reserve: how many good reps you think were still possible when the set ended. Failure means no further good rep was possible. The default target is 1–2 RIR for hard strength/hypertrophy work. If your training intentionally stays easier, change the target and use the Extended 5+ scale.'],
  ['flag','Progress up — or adjust down','If every required set reaches its rep target with enough RIR and no failures, Gym Progress can suggest progression next time. Loaded exercises normally progress by weight; bodyweight exercises progress by reps. If you only just clear the effort target, the suggested increase stays conservative; a clearly comfortable heavy exercise may justify a larger jump. Weight suggestions remain editable. A red flag can suggest fewer reps or a small load reduction for the next set. One bad exercise does not automatically make the whole workout Failure.'],
  ['flow','During the workout','Follow the active set, enter reps and RIR, and let the rest timer run. Warm-up, ramp-up, rest, unloading and stretching are timed separately. You can leave the workout screen; the live session banner at the top takes you straight back. If you stop early, choose Finish as partial to keep completed work as Aborted, or Discard workout to remove the session completely.'],
  ['calendar','Stay consistent','Motivation & reminders is optional. After a completed workout, Gym Progress suggests a next-session date; accept it, choose another date, or skip. The date appears beside next on Home, can be changed with the calendar icon, and turns red if overdue. The inactivity reminder defaults to 3 days. You can also choose the evening-before and session-day reminder times in Settings.']
];
const LV = [
  ['programme','Izveido savu programmu','Izveido treniņu dienas un pievieno vingrinājumus ar piegājieniem, atkārtojumiem, atpūtu un darba svaru. Norādi arī Equipment. Hantelēm ievadi vienas hanteles svaru un izvēlies Pair vai Single; Pair gadījumā apjoms automātiski ņem vērā abas hanteles. Heavy compound ir smags vairāku locītavu vingrinājums, piemēram, pietupiens, vilkme vai spiešana guļus. Compound ir mazāk prasīgs vairāku locītavu vingrinājums, Machine compound — trenažierī, bet Isolation galvenokārt noslogo vienu locītavu vai muskuļu grupu.'],
  ['ramp','Ramp-up atstāj Automatic režīmā','Vingrinājuma tips ir svarīgs, jo smagiem vingrinājumiem parasti vajag vairāk sagatavošanās. Automatic ņem vērā vingrinājumu, darba svaru un treniņa kontekstu. Ja līdzīga kustība jau ir iesildīta, ramp-up kļūst īsāks. Always vai Never izmanto tikai apzināti. “Remove weights” uzskaita svaru noņemšanu atsevišķi, nevis kā pasīvu atpūtu.'],
  ['rir','RIR ir slodzes sajūtas mērs','RIR nozīmē, cik kvalitatīvus atkārtojumus vēl varētu izpildīt pēc piegājiena. Failure nozīmē, ka vēl vienu kvalitatīvu atkārtojumu vairs nevarētu izpildīt. Noklusējuma mērķis ir 1–2 RIR intensīvam spēka/hipertrofijas treniņam. Ja treniņš apzināti ir vieglāks, maini mērķi un izmanto Extended 5+ skalu.'],
  ['flag','Progresē uz augšu — vai koriģē uz leju','Ja visi piegājieni sasniedz atkārtojumu mērķi ar pietiekamu RIR un bez Failure, Gym Progress var ieteikt progresiju nākamreiz. Vingrinājumiem ar svaru tā parasti palielina svaru, bet ķermeņa svara vingrinājumiem — atkārtojumu skaitu. Ja RIR mērķis sasniegts tikai nedaudz, svara pieaugums ir konservatīvāks; acīmredzami vieglam smagam vingrinājumam tas var būt lielāks. Svara ieteikumu vienmēr vari mainīt. Viens neveiksmīgs vingrinājums automātiski nepadara visu treniņu par Failure.'],
  ['flow','Treniņa laikā','Seko aktīvajam piegājienam, ievadi atkārtojumus un RIR, un izmanto atpūtas taimeri. Iesildīšanās, ramp-up, atpūta, svaru noņemšana un stiepšanās tiek uzskaitītas atsevišķi. Vari iziet no treniņa ekrāna — aktīvā treniņa josla augšpusē ļauj uzreiz atgriezties. Ja treniņu beidz priekšlaicīgi, izvēlies Finish as partial, lai saglabātu paveikto kā Aborted, vai Discard workout, lai sesiju nesaglabātu vispār.'],
  ['calendar','Saglabā regularitāti','Motivation & reminders ir izvēles funkcija. Pēc pabeigta treniņa Gym Progress iesaka nākamās sesijas datumu; pieņem to, izvēlies citu vai izlaid plānošanu. Datums Home skatā parādās pie next, to var mainīt ar kalendāra ikonu, un nokavējuma gadījumā tas kļūst sarkans. Neaktivitātes atgādinājums pēc noklusējuma ir 3 dienas. Settings vari izvēlēties arī iepriekšējā vakara un treniņa dienas atgādinājuma laiku.']
];

export function manualHtml(lang='en'){
  const items=lang==='lv'?LV:EN;
  return `<div class="manual-hero"><div class="manual-kicker">${lang==='lv'?'SĀC ŠEIT':'START HERE'}</div><h1>${lang==='lv'?'Gym Progress īsumā':'Gym Progress in 2 minutes'}</h1><p>${lang==='lv'?'Iestati programmu, trenējies un ļauj lietotnei palīdzēt ar progresiju un slodzes korekcijām.':'Set up your programme, train, and let the app help with progression and sensible load adjustments.'}</p></div>`+
    items.map(([kind,title,body],i)=>`<section class="manual-card"><div class="manual-visual">${icon(kind)}</div><div class="manual-copy"><div class="manual-number">0${i+1}</div><h2>${title}</h2><p>${body}</p></div></section>`).join('');
}
