const icon = (kind) => {
  const common='viewBox="0 0 120 82" aria-hidden="true"';
  if(kind==='start') return `<svg ${common}><circle cx="35" cy="41" r="16"/><path d="M31 41 L39 49 L54 32" class="accent"/><line x1="66" y1="29" x2="102" y2="29"/><line x1="66" y1="42" x2="96" y2="42"/><line x1="66" y1="55" x2="88" y2="55"/></svg>`;
  if(kind==='programme') return `<svg ${common}><rect x="15" y="15" width="90" height="52" rx="12"/><line x1="32" y1="31" x2="88" y2="31"/><line x1="32" y1="43" x2="78" y2="43"/><circle cx="28" cy="56" r="5"/><circle cx="45" cy="56" r="5"/><circle cx="62" cy="56" r="5"/></svg>`;
  if(kind==='ramp') return `<svg ${common}><line x1="14" y1="67" x2="108" y2="67"/><rect x="20" y="52" width="16" height="15" rx="3"/><rect x="46" y="40" width="16" height="27" rx="3"/><rect x="72" y="27" width="16" height="40" rx="3"/><path d="M22 48 L50 35 L77 21 L101 10"/><path d="M92 10 L101 10 L99 19"/></svg>`;
  if(kind==='rir') return `<svg ${common}><path d="M18 57 A42 42 0 0 1 102 57"/><line x1="60" y1="57" x2="83" y2="29"/><circle cx="60" cy="57" r="5"/><text x="18" y="74">FAIL</text><text x="92" y="74">5+</text></svg>`;
  if(kind==='down') return `<svg ${common}><path d="M18 25 L43 43 L61 34 L91 59"/><path d="M82 59 L91 59 L91 50"/><circle cx="24" cy="24" r="5"/><circle cx="91" cy="59" r="5" class="accent"/></svg>`;
  if(kind==='up') return `<svg ${common}><path d="M18 60 L43 44 L61 49 L94 20"/><path d="M84 20 L94 20 L94 30"/><circle cx="21" cy="59" r="5"/><circle cx="94" cy="20" r="5" class="accent"/></svg>`;
  if(kind==='flow') return `<svg ${common}><circle cx="23" cy="41" r="10"/><line x1="33" y1="41" x2="49" y2="41"/><circle cx="60" cy="41" r="10"/><line x1="70" y1="41" x2="86" y2="41"/><circle cx="97" cy="41" r="10"/></svg>`;
  return `<svg ${common}><rect x="23" y="18" width="74" height="52" rx="10"/><line x1="23" y1="34" x2="97" y2="34"/><line x1="40" y1="12" x2="40" y2="25"/><line x1="80" y1="12" x2="80" y2="25"/><circle cx="47" cy="50" r="4" class="accent"/><path d="M59 50 L67 58 L82 43" class="accent"/></svg>`;
};

const EN=[
 ['start','Getting started','If you have no programme, Gym Progress offers a simple three-day starter wizard. Choose your goal and experience, then optionally enter comfortable weights for about 8 good reps in squat, bench press, row and Romanian deadlift. If some reference weights are missing, the app warns you and can estimate them from the values you did enter; with no reference data it uses a conservative baseline. The generated programme is fully editable. You can dismiss the offer, build the programme manually, or run the starter wizard later from Settings. The wizard is a general starting point, not medical or individually coached advice.'],
 ['programme','Programme and equipment','Create any number of workout days and exercises. Each exercise stores sets, reps, rest, working weight, exercise type, ramp-up behaviour and equipment. Loaded exercises must have a working weight above 0 kg. Barbell weight means total loaded bar weight. Dumbbell weight means one dumbbell; choose Pair or Single so volume is calculated correctly. Bodyweight exercises use no external kg target and progress by reps. Historical workouts remain unchanged when you edit the future programme.'],
 ['ramp','Warm-up and ramp-up','A workout starts with a timed warm-up. Automatic ramp-up is recommended: Gym Progress uses exercise type, working weight, rep target and earlier similar movements to suggest practical warm-up sets. Barbell ramp-up uses coarse practical 5 kg steps; working-weight controls remain fine-grained. If removing plates or reconfiguring equipment takes time, enable Remove weights so that transition is logged separately from passive rest.'],
 ['rir','Sets, RIR and failure','Press SET COMPLETE and programmed rest starts immediately while you enter the set result. Record only fully completed reps. If you attempt another rep and cannot complete it, keep the completed-rep count and mark Failure separately. RIR means reps in reserve: how many good reps you believe were still possible. Every saved working set must have either an RIR value or Failure selected; Gym Progress highlights the effort choices if you try to save without one. The default target is 1–2 RIR, and an Extended scale is available for deliberately more submaximal training.'],
 ['down','Autoregulation and next-session adjustment','Unexpected first-set failure, repeated failure, a large rep miss or a sharp RIR drop can trigger a conservative suggestion for the next set. For externally loaded exercises, Gym Progress keeps the programmed rep target and suggests a smaller working weight; rep reductions are reserved for bodyweight exercises. When an exercise finishes with failure, the same principle can be offered separately for future sessions. These are suggestions only; you can keep the current programme.'],
 ['up','Progression','If every required working set reaches its target reps with enough RIR and no failure, Gym Progress can suggest progression. Loaded exercises usually progress by weight; bodyweight exercises by reps. Barbell progression is deliberately more sensitive than ramp-up: +2.5 kg is the normal suggestion near the target effort, while +5 kg is reserved for clearly comfortable heavy lower-body work. The proposed future target is always editable before you accept it.'],
 ['flow','Finishing, logs and progress','Warm-up, ramp-up, rest, unloading and stretching are timestamped separately. Finish as partial keeps completed work, marks the session Aborted and excludes it from Progress baselines; Discard workout removes the active session completely. Logs show session difficulty, volume and history. One isolated failed set does not automatically label the whole workout Failure; that status is reserved for repeated or systemic failure. Progress charts track Weight, Volume and e1RM.'],
 ['calendar','Scheduling, language and data','Motivation & reminders is optional. After a completed workout, Gym Progress suggests a next-session date; you can accept, change, reschedule or skip it. Reminder times are configurable. Language is selected in Settings and the entire app, including this Manual, follows that choice. Use Full backup for restorable programme, history and settings; CSV/JSON exports are for analysis. Erase exercise log data removes workout history and Progress data while keeping your programme, settings and current working weights. PWA notifications remain best-effort when the browser is fully closed.']
];
const LV=[
 ['start','Darba sākšana','Ja programma vēl nav izveidota, Gym Progress piedāvā vienkāršu trīs dienu sākuma vedni. Izvēlies mērķi un pieredzes līmeni, pēc tam, ja zini, ievadi svaru, ar kuru vari ērti izpildīt apmēram 8 kvalitatīvus atkārtojumus pietupienā, spiešanā guļus, vilkšanā pie jostas un rumāņu vilkmē. Ja daļa atsauces svaru nav ievadīta, lietotne par to brīdina un var tos aptuveni aprēķināt no ievadītajiem svariem; ja nav ievadīts neviens svars, tiek izmantots piesardzīgs sākuma līmenis. Izveidotā programma ir pilnībā rediģējama. Piedāvājumu vari noraidīt, programmu izveidot manuāli vai vedni vēlāk palaist Iestatījumos. Tā ir vispārīga sākuma programma, nevis medicīnisks vai individuāla trenera ieteikums.'],
 ['programme','Programma un inventārs','Vari izveidot jebkādu treniņu dienu un vingrinājumu skaitu. Katram vingrinājumam tiek glabāts piegājienu un atkārtojumu skaits, atpūta, darba svars, vingrinājuma tips, iesildīšanās piegājienu režīms un inventārs. Vingrinājumiem ar ārēju slodzi darba svaram jābūt lielākam par 0 kg. Stienim ievadītais svars ir pilns stieņa svars ar ripām. Hantelēm ievadi vienas hanteles svaru un norādi, vai izmanto pāri vai vienu hanteli, lai pareizi aprēķinātu apjomu. Ķermeņa svara vingrinājumiem ārējais svars netiek izmantots, un progresija notiek ar atkārtojumiem. Rediģējot nākotnes programmu, iepriekšējo treniņu dati nemainās.'],
 ['ramp','Iesildīšanās un iesildīšanās piegājieni','Treniņš sākas ar laika uzskaiti iesildīšanās posmam. Ieteicamais režīms ir automātiski iesildīšanās piegājieni: Gym Progress ņem vērā vingrinājuma tipu, darba svaru, atkārtojumu mērķi un iepriekš veiktas līdzīgas kustības. Stieņa iesildīšanās svari tiek noapaļoti praktiskos 5 kg soļos, bet darba svara manuālā regulēšana saglabājas precīza. Ja ripu noņemšana vai inventāra pārkārtošana aizņem laiku, ieslēdz svaru noņemšanas uzskaiti — tas tiek reģistrēts atsevišķi no pasīvās atpūtas.'],
 ['rir','Piegājieni, RIR un atteice','Nospiežot PIEGĀJIENS PABEIGTS, paredzētā atpūta sākas uzreiz, kamēr ievadi rezultātu. Uzskaiti tikai pilnībā pabeigtus atkārtojumus. Ja mēģini izpildīt nākamo atkārtojumu, bet to nepabeidz, atkārtojumu skaitā to neiekļauj un atsevišķi atzīmē Atteici. RIR nozīmē atkārtojumu rezervi — cik kvalitatīvus atkārtojumus, tavuprāt, vēl būtu iespējams izpildīt. Katram saglabātam darba piegājienam obligāti jāizvēlas RIR vai Atteice; ja mēģināsi saglabāt bez šīs izvēles, Gym Progress sarkanā krāsā izcels piepūles izvēles. Noklusējuma mērķis ir 1–2 RIR; apzināti vieglākam treniņam pieejama paplašināta skala.'],
 ['down','Autoregulācija un nākamā treniņa korekcija','Negaidīta atteice pirmajā piegājienā, atkārtota atteice, būtiski nesasniegts atkārtojumu mērķis vai straujš RIR kritums var izraisīt piesardzīgu ieteikumu nākamajam piegājienam. Vingrinājumiem ar ārēju slodzi Gym Progress saglabā ieprogrammēto atkārtojumu mērķi un iesaka mazāku darba svaru; atkārtojumu samazināšana paredzēta tikai ķermeņa svara vingrinājumiem. Ja vingrinājums beidzas ar atteici, to pašu principu var atsevišķi piedāvāt arī nākamajiem treniņiem. Tie vienmēr ir tikai ieteikumi; pašreizējo programmu vari saglabāt.'],
 ['up','Progresija','Ja visi nepieciešamie darba piegājieni sasniedz atkārtojumu mērķi ar pietiekamu RIR un bez atteices, Gym Progress var piedāvāt progresiju. Vingrinājumiem ar ārēju svaru tā parasti palielina svaru, bet ķermeņa svara vingrinājumiem — atkārtojumus. Stieņa progresija ir jutīgāka nekā iesildīšanās svaru soļi: tuvu mērķa piepūlei tipisks ieteikums ir +2,5 kg, savukārt +5 kg tiek rezervēti skaidri viegli izpildītam smagam apakšdaļas bāzes vingrinājumam. Pirms apstiprināšanas nākamā mērķa vērtību vienmēr vari rediģēt.'],
 ['flow','Treniņa pabeigšana, žurnāls un progress','Iesildīšanās, iesildīšanās piegājieni, atpūta, svaru noņemšana un stiepšanās tiek uzskaitīti atsevišķi. Pabeigt kā nepilnu saglabā paveikto, atzīmē sesiju kā Pārtrauktu un neizmanto to Progresa bāzes salīdzinājumos; Atmest treniņu aktīvo sesiju pilnībā dzēš. Žurnālā redzama treniņa grūtība, apjoms un vēsture. Viena izolēta atteice automātiski nepadara visu treniņu par Atteici — šis statuss paredzēts atkārtotai vai sistēmiskai atteicei. Progresa grafikos pieejams Svars, Apjoms un e1RM.'],
 ['calendar','Plānošana, valoda un dati','Motivācija un atgādinājumi ir izvēles funkcija. Pēc pabeigta treniņa Gym Progress iesaka nākamā treniņa datumu; to vari pieņemt, mainīt, pārplānot vai izlaist. Atgādinājumu laikus var mainīt. Valodu izvēlas Iestatījumos, un visa lietotne, tostarp šī Pamācība, seko izvēlētajai valodai. Pilna rezerves kopija paredzēta programmas, vēstures un iestatījumu atjaunošanai; CSV/JSON eksports — analīzei. Funkcija Dzēst treniņu žurnāla datus izdzēš treniņu vēsturi un Progresa datus, bet saglabā programmu, iestatījumus un pašreizējos darba svarus. PWA paziņojumi joprojām ir iespējami tikai pēc labākās iespējas, ja pārlūks ir pilnībā aizvērts.']
];

export function manualHtml(lang='en'){
  const items=lang==='lv'?LV:EN;
  return `<div class="manual-hero"><div class="manual-kicker">${lang==='lv'?'PAMĀCĪBA':'MANUAL'}</div><h1>${lang==='lv'?'Gym Progress pamācība':'Gym Progress manual'}</h1><p>${lang==='lv'?'Programma, treniņa plūsma, progresija un datu drošība vienuviet.':'Programme, workout flow, progression and data safety in one place.'}</p></div>`+
    items.map(([kind,title,body],i)=>`<section class="manual-card"><div class="manual-visual">${icon(kind)}</div><div class="manual-copy"><div class="manual-number">${String(i+1).padStart(2,'0')}</div><h2>${title}</h2><p>${body}</p></div></section>`).join('');
}
