import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const errors=[];
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>{const f=path.join(dir,e.name);if(e.name==='node_modules')return[];return e.isDirectory()?walk(f):[f];});
const files=walk(root),read=r=>fs.readFileSync(path.join(root,r),'utf8');
const app=read('app.js'),css=read('styles.css'),sw=read('sw.js'),pkg=JSON.parse(read('package.json'));
if(pkg.version!=='1.5.3'||!app.includes("APP_VERSION='1.5.3'")||!sw.includes('gym-progress-pwa-v1.5.3'))errors.push('v1.5.3 version markers are inconsistent');
for(const rel of ['exercise-identity.js','exercise-catalogue.js','exercise-catalogue.json','exercise-migration-map.js','exercise-migration-map.json','performance-rules.json','performance-rule-cases.json','supabase/SUPABASE_EXERCISE_CATALOGUE_AND_COMPARISON.sql','supabase/SUPABASE_BACKUP_BEFORE_EXERCISE_MIGRATION.md','supabase/SUPABASE_PRE_MIGRATION_CHECK.sql','supabase/SUPABASE_POST_MIGRATION_VERIFY.sql']) if(!fs.existsSync(path.join(root,rel)))errors.push(`missing release asset: ${rel}`);
if(!app.includes("value:`u:${id}`")||!app.includes("value:`p:${e.programmeExerciseId}`"))errors.push('Progress does not use stable user/programme exercise IDs');
if(!app.includes("if(!(ses?.status==='COMPLETE'||(ses?.status==='ABORTED'&&fullyCompleted)))continue"))errors.push('aborted fully-completed exercises are not included in Progress');
if(!app.includes('qualifyingE1rm')||!read('exercise-identity.js').includes('effective>10'))errors.push('comparison-grade e1RM rules missing');
if(!app.includes('compareWithFriends')||!app.includes('comparisonPointsForSession'))errors.push('programme-selected friend comparison missing');
if(!app.includes('comparisonPointsForSelectedHistory')||!app.includes('syncComparisonHistory')||!read('social-api.js').includes('social_replace_exercise_comparison_points'))errors.push('retroactive comparison-history sync missing');
if(!app.includes('TrackingMode.TIME_ONLY')||!app.includes("rt.phase='TIMED_SET'"))errors.push('timed/mat exercise flow missing');
if(!app.includes('supersetGroupId')||!app.includes('SUPERSET_IMMEDIATE'))errors.push('superset flow missing');
if(!app.includes('maxRampUpSets')||!read('exercise-library.js').includes('barbellPlateFriendlyRamp'))errors.push('max/plate-friendly ramp logic missing');
if(!app.includes('disableRampPermanently')||!app.includes('renderNextInfo'))errors.push('ramp permanent-disable or Next panel missing');
if(!app.includes("kind==='warning30'")||!app.includes("kind==='countdown'"))errors.push('updated audio cue patterns missing');
if(!app.includes('renderTrackerCard')||!app.includes('setTrackerAmount')||!app.includes('checkTrackerReminders'))errors.push('Tracker functionality incomplete');
if(!app.includes('sentTrackerReminderKeys')||!app.includes('(4*60)')||!css.includes('.tracker-card-accent')||!css.includes('.tracker-row.behind')||!css.includes('.tracker-row.done'))errors.push('Tracker visual/4-hour reminder follow-up missing');
if(!app.includes('closeDialog();startWorkout(id)'))errors.push('Start Anyway does not close its warning');
if(!app.includes('await afterRest()')||!app.includes('async function skipExercise()'))errors.push('Skip exercise direct transition missing');
if(!app.includes('Remove permanently')||!app.includes('Skip today'))errors.push('new ramp-up wording missing');
if(!app.includes('pulse-reps-badge"><span>${set.targetReps}</span> REPS'))errors.push('active pulse rep target is not prominent');
if(!app.includes('catalogueGlobeSvg')||!css.includes('.catalogue-status.linked{color:#39b86a')||!css.includes('.catalogue-status.local{color:#858891'))errors.push('requested catalogue globe linked/local styling missing');
if(app.includes('Use existing ·')||app.includes('Existing exercise'))errors.push('obsolete own-exercise picker remains in exercise creation');
if(!app.includes('If no catalogue match is selected')||!app.includes('Exercise type')||!app.includes('Compare with friends'))errors.push('direct catalogue-as-you-type exercise creation metadata missing');
if(app.includes('class="card advanced-settings"'))errors.push('settings are still hidden in generic Advanced section');
if(!app.includes('class="app-version">Gym Progress PWA v${APP_VERSION}</div>`'))errors.push('version footer missing at bottom of Settings');
if(!css.includes('.chart-axis{font-size:12px')||!app.includes('T=16,B=14')||!app.includes('k kg'))errors.push('current chart geometry/unit formatting missing');
if(!css.includes('.setting-toggle-row')||!app.includes('lastSetZeroRirAcceptable'))errors.push('last-set RIR setting/toggle missing');
if(!app.includes("saveRecoveryState(loaded,'pre-identity-migration-v1')")||!app.includes('refusing to overwrite IndexedDB')||!app.includes('do not immediately write an empty'))errors.push('local-data migration safeguards missing');

const identity=read('exercise-identity.js');
if(!identity.includes('a display-name similarity alone must never do so')||!identity.includes('const canonical=template.exerciseKey?'))errors.push('generic legacy migration can still auto-link by display name');
const catalogue=JSON.parse(read('exercise-catalogue.json')),migration=JSON.parse(read('exercise-migration-map.json'));
if(catalogue.families?.length!==27||catalogue.exercises?.length!==191)errors.push('catalogue count mismatch');
if(catalogue.exercises.filter(x=>x.friendE1rmEligible).length!==9)errors.push('friend-comparable catalogue count mismatch');
if(migration.users?.length!==32||migration.programmeOccurrences?.length!==42)errors.push('reviewed migration count mismatch');
if(migration.users.some(x=>!['LINK','KEEP_LOCAL'].includes(x.mappingStatus)))errors.push('reviewed migration still has unresolved mappings');
const sql=read('supabase/SUPABASE_EXERCISE_CATALOGUE_AND_COMPARISON.sql');
if(!sql.includes('begin;')||!sql.includes('commit;')||!sql.includes('grant select, insert, update, delete on public.exercise_comparison_points to authenticated')||!sql.includes('social_replace_exercise_comparison_points'))errors.push('Supabase migration transaction/API grants/retroactive sync RPC missing');
const shellMatch=sw.match(/const APP_SHELL = (\[[\s\S]*?\]);/);if(!shellMatch)errors.push('APP_SHELL not found');else{const shell=JSON.parse(shellMatch[1]);for(const rel of ['./exercise-identity.js','./exercise-catalogue.js','./exercise-catalogue.json','./exercise-migration-map.js','./exercise-migration-map.json'])if(!shell.includes(rel))errors.push(`service worker missing ${rel}`);for(const item of shell){const rel=item.replace(/^\.\//,'');if(!fs.existsSync(path.join(root,rel)))errors.push(`missing service-worker asset: ${item}`);}}
for(const f of files.filter(f=>/\.(?:js|mjs)$/.test(f))){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});if(r.status!==0)errors.push(`JavaScript syntax error in ${path.relative(root,f)}: ${r.stderr.trim()}`);}
const rr=spawnSync(process.execPath,[path.join(root,'tools','validate-rules.mjs')],{encoding:'utf8'});if(rr.status!==0)errors.push(`performance-rule cases failed: ${(rr.stderr||rr.stdout).trim()}`);
if(errors.length){console.error(errors.join('\n'));process.exit(1);}console.log(`OK: ${files.length} PWA files checked`);
